apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dep
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: amitow/nginx:v1
        imagePullPolicy: Always
        name: hello-dep
        ports:
        - containerPort: 8080
