apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rcp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: amitow/nginx:v1
        imagePullPolicy: Always
        name: hello-dep
        ports:
        - containerPort: 8080
